<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OFFICE PHONE_form-control form</name>
   <tag></tag>
   <elementGuidId>37adc0ed-2a18-4abd-b6f4-208ce95cd388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.form-control-sm.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-nav-0-panel&quot;)/div[@class=&quot;tab-lbl_account_information ng-star-inserted&quot;]/scrm-field-layout[1]/form[@class=&quot;create field-layout&quot;]/div[@class=&quot;form-row align-items-center ng-star-inserted&quot;]/div[@class=&quot;col form-group m-0 pl-3 pb-2 pr-3 ng-star-inserted&quot;]/div[@class=&quot;d-flex ng-star-inserted&quot;]/div[@class=&quot;flex-grow-1 text-break&quot;]/scrm-field[@class=&quot;field field-mode-create field-name-phone_office field-type-phone&quot;]/scrm-dynamic-field[@class=&quot;dynamic-field dynamic-field-mode-edit dynamic-field-name-phone_office dynamic-field-type-phone ng-star-inserted&quot;]/scrm-varchar-edit[@class=&quot;ng-star-inserted&quot;]/input[@class=&quot;form-control form-control-sm ng-untouched ng-pristine ng-valid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ngb-nav-0-panel']/div/scrm-field-layout/form/div/div[2]/div[2]/div/scrm-field/scrm-dynamic-field/scrm-varchar-edit/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/scrm-field/scrm-dynamic-field/scrm-varchar-edit/input</value>
   </webElementXpaths>
</WebElementEntity>
