<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Street_form-control form-control-sm ng-untouched ng-pristine ng-valid</name>
   <tag></tag>
   <elementGuidId>09083e18-a1ae-4469-b8f6-32746ba85456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>scrm-dynamic-field.dynamic-field.dynamic-field-mode-edit.dynamic-field-name-shipping_address_street.dynamic-field-type-varchar > scrm-varchar-edit.ng-star-inserted > input.form-control.form-control-sm.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-nav-0-panel&quot;)/div[@class=&quot;tab-lbl_account_information ng-star-inserted&quot;]/scrm-field-layout[1]/form[@class=&quot;create field-layout&quot;]/div[@class=&quot;form-row align-items-center ng-star-inserted&quot;]/div[@class=&quot;col form-group m-0 pl-3 pb-2 pr-3 ng-star-inserted&quot;]/div[@class=&quot;d-flex ng-star-inserted&quot;]/div[@class=&quot;flex-grow-1 text-break&quot;]/scrm-field[@class=&quot;field field-mode-create field-name-shipping_address field-type-grouped-field&quot;]/scrm-dynamic-field[@class=&quot;dynamic-field dynamic-field-mode-edit dynamic-field-name-shipping_address dynamic-field-type-grouped-field ng-star-inserted&quot;]/scrm-group-field[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;align-items-start d-flex field-group flex-column h-100 justify-content-start ng-star-inserted&quot;]/div[@class=&quot;field-group-item d-flex flex-column justify-content-end h-100 w-100 ng-star-inserted&quot;]/span[@class=&quot;field-group-field pr-1 ng-star-inserted&quot;]/scrm-dynamic-field[@class=&quot;dynamic-field dynamic-field-mode-edit dynamic-field-name-shipping_address_street dynamic-field-type-varchar&quot;]/scrm-varchar-edit[@class=&quot;ng-star-inserted&quot;]/input[@class=&quot;form-control form-control-sm ng-untouched ng-pristine ng-valid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ngb-nav-0-panel']/div/scrm-field-layout/form/div[4]/div[2]/div[2]/div/scrm-field/scrm-dynamic-field/scrm-group-field/div/div/span[2]/scrm-dynamic-field/scrm-varchar-edit/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/scrm-field/scrm-dynamic-field/scrm-group-field/div/div/span[2]/scrm-dynamic-field/scrm-varchar-edit/input</value>
   </webElementXpaths>
</WebElementEntity>
